### ISSUE TITLE
Creating ticket using the API with custom create date

### ISSUE THREAD

**Issue by puneet0191** [DeskPRO/deskpro-api-php#17]
I am currently trying to import data from a third party tool to Deskpro, while importing tickets and comments from some other system, I would like to retain the date of issue creation, date when the comment on the ticket was done, and use the same dates while importing them into Deskpro using the API, what currently happens is that I don't have any option where I can modify the create_date for a ticket or a note/message so when ever I create a new ticket using the API, the default date that it takes is the system date, no matter when the issue was created. 

If anyone was able to find a work around for this scenario or were able to get this working using the Deskpro API, your help would be really appreciated. 

Thanks,
Puneet

**Comment by chrispadfield** [comment]
The DeskPRO API is not really the right tool for importing tickets like this, for the reason you mention.

We have an importer tool instead that does let you set dates. You convert your data into a standard JSON format that DeskPRO can then import from. Details are here

https://github.com/DeskPRO/deskpro-importer-tools

**Comment by puneet0191** [comment]
@chrispadfield I tried using the deskpro-importer-tools since I have to do the import using the custom way, because the tool from which I need to import tickets is not available as part of the importer. 

I already have the scripts to generate the json files for each ticket that I want to import, I have followed all the instructions mentioned here for custom import
https://github.com/DeskPRO/deskpro-importer-tools/blob/master/custom/README.md 
not sure what is it that I am missing, but even after running the importer on the json's I am not able to get the ticket imported into deskpro. I will create a new issue on that repo, but if you can help, It would be really helpful.
